Repository conda-forge/amrex-feedstock, pull requests merged in 2025-07, with the labels that each got.

#53 AMReX 25.07
  recipe/recipe.yaml
Labels: automerge

#54 Bot Config: Ignore `v2024` Tag
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-osx.yml
  .azure-pipelines/azure-pipelines-win.yml
  .scripts/build_steps.sh
  .scripts/run_docker_build.sh
  .scripts/run_osx_build.sh
  .scripts/run_win_build.bat
  conda-forge.yml
Labels: automerge, bug

#56 MNT: rerender: GCC 14 / Clang 19
  .ci_support/linux_64_mpimpich.yaml
  .ci_support/linux_64_mpinompi.yaml
  .ci_support/linux_64_mpiopenmpi.yaml
  .ci_support/linux_aarch64_mpimpich.yaml
  .ci_support/linux_aarch64_mpinompi.yaml
  .ci_support/linux_aarch64_mpiopenmpi.yaml
  .ci_support/linux_ppc64le_mpimpich.yaml
  .ci_support/linux_ppc64le_mpinompi.yaml
  .ci_support/linux_ppc64le_mpiopenmpi.yaml
  .ci_support/osx_64_mpimpich.yaml
  .ci_support/osx_64_mpinompi.yaml
  .ci_support/osx_64_mpiopenmpi.yaml
  .ci_support/osx_arm64_mpimpich.yaml
  .ci_support/osx_arm64_mpinompi.yaml
  .ci_support/osx_arm64_mpiopenmpi.yaml
  .gitattributes
  recipe/recipe.yaml
Labels: automerge

#57 AMReX: SP Build
  .azure-pipelines/azure-pipelines-linux.yml
  .azure-pipelines/azure-pipelines-osx.yml
  .azure-pipelines/azure-pipelines-win.yml
  .ci_support/linux_64_amrex_precisiondpmpimpich.yaml
  .ci_support/linux_64_amrex_precisiondpmpinompi.yaml
  .ci_support/linux_64_amrex_precisiondpmpiopenmpi.yaml
  .ci_support/linux_64_amrex_precisionspmpimpich.yaml
  .ci_support/linux_64_amrex_precisionspmpinompi.yaml
  .ci_support/linux_64_amrex_precisionspmpiopenmpi.yaml
  .ci_support/linux_aarch64_amrex_precisiondpmpimpich.yaml
  .ci_support/linux_aarch64_amrex_precisiondpmpinompi.yaml
  .ci_support/linux_aarch64_amrex_precisiondpmpiopenmpi.yaml
  .ci_support/linux_aarch64_amrex_precisionspmpimpich.yaml
  .ci_support/linux_aarch64_amrex_precisionspmpinompi.yaml
  .ci_support/linux_aarch64_amrex_precisionspmpiopenmpi.yaml
  .ci_support/linux_ppc64le_amrex_precisiondpmpimpich.yaml
  .ci_support/linux_ppc64le_amrex_precisiondpmpinompi.yaml
  .ci_support/linux_ppc64le_amrex_precisiondpmpiopenmpi.yaml
  .ci_support/linux_ppc64le_amrex_precisionspmpimpich.yaml
  .ci_support/linux_ppc64le_amrex_precisionspmpinompi.yaml
  .ci_support/linux_ppc64le_amrex_precisionspmpiopenmpi.yaml
  .ci_support/osx_64_amrex_precisiondpmpimpich.yaml
  .ci_support/osx_64_amrex_precisiondpmpinompi.yaml
  .ci_support/osx_64_amrex_precisiondpmpiopenmpi.yaml
  .ci_support/osx_64_amrex_precisionspmpimpich.yaml
  .ci_support/osx_64_amrex_precisionspmpinompi.yaml
  .ci_support/osx_64_amrex_precisionspmpiopenmpi.yaml
  .ci_support/osx_arm64_amrex_precisiondpmpimpich.yaml
  .ci_support/osx_arm64_amrex_precisiondpmpinompi.yaml
  .ci_support/osx_arm64_amrex_precisiondpmpiopenmpi.yaml
  .ci_support/osx_arm64_amrex_precisionspmpimpich.yaml
  .ci_support/osx_arm64_amrex_precisionspmpinompi.yaml
  .ci_support/osx_arm64_amrex_precisionspmpiopenmpi.yaml
  .ci_support/win_64_amrex_precisiondp.yaml
  .ci_support/win_64_amrex_precisionsp.yaml
  README.md
  recipe/build.bat
  recipe/build.sh
  recipe/conda_build_config.yaml
  recipe/recipe.yaml
Labels: enhancement
